---
application:
  name: "random-testcase-generator"
  project: "Random-testcase-generator"
  organization: "QoveryCommunity"
routers:
- name: "main-random-testcase-generator"
   custom_domains:
  - branch: master
    domain: randomtc.xyz
  routes:
  - application_name: "random-testcase-generator"
    paths:
    - "/*"
